### ISSUE TITLE
rtcmserver 

### ISSUE THREAD

**Issue by gerritflysense** [eringerli/RpiNtripBase#3]
fatal: repository 'https://github.com/aortner/rtcmserver/' not found
fatal: clone of 'https://github.com/aortner/rtcmserver' into submodule path '/home/pi/RpiNtripBase/external/rtcmserver' failed
Failed to clone 'external/rtcmserver'. Retry scheduled
Cloning into '/home/pi/RpiNtripBase/external/rtcmserver'...

**Comment by gerritflysense** [comment]
Hope you guys can help please.

**Comment by gerritflysense** [comment]
Issue resolved, thanks @aortner.

**Comment by gerritflysense** [comment]
Issue resolved, thanks @aortner.

**Comment by RKwalter** [comment]
issue is still there.
